URLS = [
    "https://www.karton.eu/Unsere-Kartonagen/",
]
LinksProDurchlauf = 100
AlleExportieren = true
TeilExporte = true
InfluexUrl = "http://localhost:8086"
InfluexOrg = "karton.eu"
InfluexBucket = "karton.eu"