URLS = [
    "https://ecoon.de/product-sitemap.xml/",
    # "https://www.karton.eu/Unsere-Kartonagen/",
]
LinksProDurchlauf = 100
AlleExportieren = true
TeilExporte = false
InfluexUrl = "http://localhost:8086"
InfluexOrg = "karton.eu"
InfluexBucket = "karton.eu"